### ISSUE TITLE
## *Create a list of Rehearsal Room Members*

### ISSUE THREAD

**Issue by gadmel** [gadmel/Rehearsal-Room#1]
As an **administrator**
I need a **list to see all the rehearsal room (RR in further) members**
so that I can **scroll through all RR members and recognize each's name, role, band, music instruments, repetition time(s) and a big photo**

## *Description (Text, Scribble, Wireframe, Design)*

Horizontally scrollable list of membercards with a big photo, names of the member himself and his band, repetition time(s), badge of his role(s),
 
### Acceptance criteria

- [x] A list of visually separatable member cards with all a.m. information on a single member.

### Tasks

 - [x] Initialize a new React-Project. Think on the future division of the Project in two parts: server and client.
 - [x] Create a page-component (section) in the client part for the members-visualisation. Use styled-components.
 - [x] Make a .json with mock data on members
 - [x] Create all the periphery: .gitignore, .prettierrc etc. Prepare (a mask for) GlobalStyles.js

Size:M

**Comment by hagenbrandt** [comment]
Das grid könnte global gesetzt werden, ansonsten passt alles.
