### ISSUE TITLE
Re-order the application structure

### ISSUE THREAD

**Issue by gadmel** [gadmel/Rehearsal-Room#10]
### Acceptance criteria

 - [ ] There are much more less directories in the project.
 - [ ] useForm hook is in the same directory of CreateForm component.
 - [ ] The structure of the project is clear and easy to see through.

### Tasks

 - [ ] Refactor it!.

Size: M
