### ISSUE TITLE
## *Create a form for adding new members*

### ISSUE THREAD

**Issue by gadmel** [gadmel/Rehearsal-Room#2]
As an **administrator**
I need **a way to add new members to the RR.**
so that I can **add input information on a new member in the form** which **appears in the bar below the members-list instead of the container with symbols, such as a add-new-member-icon by click on this mentioned icon. A cross-button (closing the form without submiting) as well as submit button should be recognizable**

## *Description (Text, Scribble, Wireframe, Design)*

 - a vertical grid of rows (70 / 30) with the members-visualization in the top and control bars in the bottom. By click on the option-button a form apears instead of the control bar.
 
### Acceptance criteria

 - [x] Control bar with an Add-New-Member icon
 - [x] A form with inputs for name (text), band, instruments, roles.

### Tasks

 - [x] Create Grid 
 - [x] Create control bar with icons for navigation
 - [x] Create form as described.

Size: L
