### ISSUE TITLE
## *Create a server with database for RR members with respective model and route*

### ISSUE THREAD

**Issue by gadmel** [gadmel/Rehearsal-Room#3]
As an **administrator**
I need that **all the members managment will be saved and updated in a database**
so that I can **grant an access to the dedicate information to authorized users**

## *Description (Text, Scribble, Wireframe, Design)*

Back-end feature
 
### Acceptance criteria

- [x] Using the client app's submit-form updates the server-data.
- [x] Updates are seen in the visualisation (member-cards-list)

### Tasks

 - [ ] Initialize a server in the respective division of the app.
- [ ] Apply Mongoose for database.
- [ ] Create a model for members
- [ ] Create a route for members
- [ ] Build in CORS
- [x] Handle by situation to make the server work with the client properly

Size: L

**Comment by gadmel** [comment]
This issue have been solved along the way of creating the create form for new members. A firebase database have been implemented instead of a server: the acceptance criteria are fulfilled so.
