### ISSUE TITLE
Create a form for editing an existing member

### ISSUE THREAD

**Issue by gadmel** [gadmel/Rehearsal-Room#4]
As an **administrator**
I need a **to correct information on existing members**
so that I can **edit existing information by click on the respective symbol on the control panel**

## *Description (Text, Scribble, Wireframe, Design)*

A form of inputs with pre-filled former data on the member opens by click on the respective icon on the control panel in the container where the control panel have been.
 
### Acceptance criteria

- [ ] A form has the pre-filled data on the member to be edited.
- [ ] There is a Close-button for going back without changes.

### Tasks

 - [ ] Create a form as described.

Size:S
