### ISSUE TITLE
Build in a calendar for repetitive events (rehearsals)

### ISSUE THREAD

**Issue by gadmel** [gadmel/Rehearsal-Room#5]
As an **administrator/musician**
I need **a calendar to see how the RR is divided into repetition times**
so that I can **see on the week-calendar which day of the week is assigned to which band**

## *Description (Text, Scribble, Wireframe, Design)*

 - A Grid of 7 columns representing day of the week with vertical "progress bars" for the times of the day filled with the band logo it taking.
 
### Acceptance criteria

 - [ ] Calendar with week-bulks 
 - [ ] Visualisation of the assignments of the bands to the repetition times.

### Tasks

 - [ ] Inform about Google Calendar API
 - [ ] Try to build in this API
 - [ ] Create visualisation of Calendar Events (repetition) on the week raster.
 - [ ] Mock the data on the actual repetition week plan.

Size: L
